name=FreqCountESPgate
version=1.0
author=siliconvalley4066
maintainer=siliconvalley4066
sentence=FreqCount measures the frequency of a signal by counting the number of pulses during a fixed time.
paragraph=
category=Signal Input/Output
url=https://harahore.g2.xrea.com/arduino/FreqCountESPgate.html
architectures=*
